apiVersion: apps/v1
kind: Deployment
metadata:
  name: connectivity-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connectivity-exporter
  template:
    metadata:
      labels:
        app: connectivity-exporter
    spec:
      containers:
      - name: exporter
        image: your-registry/connectivity-exporter:latest
        ports:
        - containerPort: 9090
        env:
        - name: CONFIG
          value: /app/config.yaml
        - name: INTERVAL
          value: "45"
        - name: PORT
          value: "9090"
        volumeMounts:
        - name: config-volume
          mountPath: /app
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: connectivity-exporter-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: connectivity-exporter-config
data:
  config.yaml: |
    endpoints:
      - url: https://google.com/generate_204
        expect: 204
      - url: http://cp.cloudflare.com/generate_204 
        expect: 204
      - url: http://edge-http.microsoft.com/captiveportal/generate_204
        expect: 204
      - url: http://connectivity-check.ubuntu.com
        expect: 204
      - url: http://connect.rom.miui.com/generate_204
        expect: 204
      - url: http://www.gstatic.com/generate_204
        expect: 204
      - url: http://www.apple.com/library/test/success.html
        expect: 200
      - url: http://spectrum.s3.amazonaws.com/kindle-wifi/wifistub.html
        expect: 200
      - url: http://detectportal.firefox.com/success.txt
        expect: 200
      - url: http://www.msftncsi.com/ncsi.txt
        expect: 200
      - url: http://network-test.debian.org/nm
        expect: 200
      - url:  http://nmcheck.gnome.org/check_network_status.txt
        expect: 200

---
apiVersion: v1
kind: Service
metadata:
  name: connectivity-exporter
spec:
  selector:
    app: connectivity-exporter
  ports:
  - name: http
    port: 9090
    targetPort: 9090
